#:schema https://mise.jdx.dev/schema/mise.json

[tools]
starship = "latest"
claude-code = "latest"
codex = "latest"
opencode = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go", "node"]
