#:schema https://starship.rs/config-schema.json

add_newline = false
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$status$cmd_duration"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](yellow)"

[git_branch]
format = "[$branch]($style) "
style = "bold green"

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1
format = "[ $path]($style) "

[cmd_duration]
format = "[$duration]($style) "

[line_break]
disabled = true

[status]
disabled = false
symbol = "✘ "
